# : Inferential Statistics
#### Get the piece of the data- analyze the data- apply these inferential statistics and whatever the results we get- applied to the entire population- That's what we call it as inferential statistics

### : Division of Inferential Statistics
#### 1] Confidence Interval
#### 2] Hypothesis Testing
#### 3] Statistical Tests

## 1] Confidence Interval
#### The range is called interval. The probability associated with this interval we call it as confidence.
#### Therefore it is the range of values to be associated with the likelihood/probability/confidence.

### Q] To calculate T-value for confidence interval 95% and n=140

In [1]:
from scipy import stats
stats.t.ppf(0.975, df=139) # ppf(percent point function)
#(1-alpha)=95%   i.e alpha = 5% , alpha/2 = 2.5% ; (95 + 2.5 = 97.5%) i.e 0.975 and df =(n-1) i.e (140 - 1) = 139

1.977177724476122

## 2] Hypothesis Testing
#### Hypothesis : just an intution.
#### Null Hypothesis(Ho) : No change/ The current process.
#### Alternate hypothesis(Ha) : Statement of change/ alternate process to be replaced.
#### p-value : is the metric to measure the confidence.
#### Assumption of p-value : It tries to prove that the Null Hypothesis is True. 

### Q] t-test for 1-Sample

In [2]:
# this code will give value of both t-value and p-value
import pandas as pd

data = pd.Series([2,4,6,8,10]) #this is sample 1

stats.ttest_1samp(data,data.mean())
#statistics is the t-value and p-value(of both sides, if we want for 1-side go for pvalue/2)

Ttest_1sampResult(statistic=0.0, pvalue=1.0)

### Q] t-test for 2-Sample

In [3]:
Control = pd.Series([20,40,56,78,4,5,95]) # sample 1
Treat = pd.Series([45,56,89,12,23,78,12]) # Sample 2
stats.ttest_ind(Control, Treat) # ind = independent

Ttest_indResult(statistic=-0.13592462803701275, pvalue=0.8941344509861002)

## 3] Statistical Test
#### A] 1-Sample (Dependent) ==> a) t-test (Mean/Avg)  b) Proportion (%) c) Paired (previous comparing)
#### B] 2-Sample (Independent) ==> a) t-test (Mean/Avg) b) Proportion (%)
#### C] ANOVA (Independent)
#### D] Chi-Square test
#### E] Regression

## D] Chi-Square Test
#### Purpose to find if there is any association between 2 qualitative feature

In [4]:
import seaborn as sns
import pandas as pd
import scipy.stats as stats

In [5]:
sns.get_dataset_names()
#make sure internet is working to load the dataset

['anagrams',
 'anscombe',
 'attention',
 'brain_networks',
 'car_crashes',
 'diamonds',
 'dots',
 'exercise',
 'flights',
 'fmri',
 'gammas',
 'geyser',
 'iris',
 'mpg',
 'penguins',
 'planets',
 'tips',
 'titanic']

In [6]:
tips = sns.load_dataset('tips')
tips

total_bill   tip     sex smoker   day    time  size
0         16.99  1.01  Female     No   Sun  Dinner     2
1         10.34  1.66    Male     No   Sun  Dinner     3
2         21.01  3.50    Male     No   Sun  Dinner     3
3         23.68  3.31    Male     No   Sun  Dinner     2
4         24.59  3.61  Female     No   Sun  Dinner     4
..          ...   ...     ...    ...   ...     ...   ...
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

[244 rows x 7 columns]

In [7]:
tips.describe()

total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [8]:
tips.groupby('smoker').mean()

total_bill       tip      size
smoker                                
Yes      20.756344  3.008710  2.408602
No       19.188278  2.991854  2.668874

In [9]:
tips.groupby('day').mean()

total_bill       tip      size
day                                 
Thur   17.682742  2.771452  2.451613
Fri    17.151579  2.734737  2.105263
Sat    20.441379  2.993103  2.517241
Sun    21.410000  3.255132  2.842105

In [10]:
tips[tips['size']==tips['size'].max()]

total_bill  tip     sex smoker   day    time  size
125       29.80  4.2  Female     No  Thur   Lunch     6
141       34.30  6.7    Male     No  Thur   Lunch     6
143       27.05  5.0  Female     No  Thur   Lunch     6
156       48.17  5.0    Male     No   Sun  Dinner     6

In [11]:
tips.groupby('smoker')['day'].value_counts()

smoker  day 
Yes     Sat     42
        Sun     19
        Thur    17
        Fri     15
No      Sun     57
        Thur    45
        Sat     45
        Fri      4
Name: day, dtype: int64

In [12]:
tips.day.unique()

['Sun', 'Sat', 'Thur', 'Fri']
Categories (4, object): ['Sun', 'Sat', 'Thur', 'Fri']

In [13]:
tips.nunique()

total_bill    229
tip           123
sex             2
smoker          2
day             4
time            2
size            6
dtype: int64

In [14]:
smoker_data =  pd.crosstab(tips.sex, tips.smoker)
smoker_data

smoker  Yes  No
sex            
Male     60  97
Female   33  54

In [15]:
stats.chi2_contingency(smoker_data)

(0.008763290531773594,
 0.925417020494423,
 1,
 array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [16]:
# NULL hypothesis(Ho): There is no association between the smoker and sex.
# Alternate hypothesis(Ha): There is association between the smoker and sex.
# pval <0.05 we reject Ho
# df = (n-1)(n1 -1) where n= total no. of row n1 = total no of column

In [17]:
chi_value, pval, df, expected_value = stats.chi2_contingency(smoker_data)
print('Ch-squared value: {}\nDegree of Freedom: {}\nExpected value: {}.'.format(chi_value, pval, df, expected_value))

Ch-squared value: 0.008763290531773594
Degree of Freedom: 0.925417020494423
Expected value: 1.


In [18]:
sex_time = pd.crosstab(tips.sex, tips.time)
sex_time

time    Lunch  Dinner
sex                  
Male       33     124
Female     35      52

In [19]:
stats.chi2_contingency(sex_time)

(9.343808982970623,
 0.002237400118075248,
 1,
 array([[ 43.75409836, 113.24590164],
        [ 24.24590164,  62.75409836]]))

## A] & B] T-test
#### Purpose to find if there is any significance difference between two groups
* 1 sample t-test
* 2 sample t-test
* Paired t-test

### * 1-Sample T-test

In [20]:
test_scores = [60,40,45,78,15,46,79,60,56,89,45,86,79,48,50]
len(test_scores)

15

In [21]:
import numpy as np
from scipy import stats

In [22]:
np.mean(test_scores) # population avg score

58.4

In [23]:
random_test_score = np.random.choice(test_scores, 8)
random_test_score

array([86, 50, 56, 45, 79, 56, 45, 79])

In [24]:
stats.ttest_1samp(test_scores,58.4 )

Ttest_1sampResult(statistic=0.0, pvalue=1.0)

In [25]:
t_score, p_value = stats.ttest_1samp(test_scores,58.4 )
print('t_score: {}.\np_value: {}'.format(t_score, p_value))

t_score: 0.0.
p_value: 1.0


In [26]:
# Ho : There is no significance difference in the average test_scores.
# Ha : There is a significance difference in the average test_scores.

In [27]:
if p_value<=0.05:
    print("We reject the Null hypothesis(Ho) saying that there is a significance difference in the average test_scores.")
else:
    print("We do not reject null hypothesis saying that there is no significance difference in the average test_scores.")

We do not reject null hypothesis saying that there is no significance difference in the average test_scores.


### * 2-Sample t-test

In [28]:
class_A = [50,80,78,98,45,86,56,89,90,60]
class_B = [78,45,89,48,78,68,88,49,90,70]

In [29]:
# Ho : The avg marks of class B is greater than class A.
# Ha : The avg marks of class B is not greater than class A.

In [30]:
t_score, p_val = stats.ttest_ind(class_A,class_B)

In [31]:
if p_val<=0.05:
    print('We reject the Null hypothesis saying that the avg marks of class B is not greater than class A.')
else:
    print('We do not reject the Null hypothesis saying that the avg marks of class B is greater than class A.')

We do not reject the Null hypothesis saying that the avg marks of class B is greater than class A.


In [32]:
print('t_score: {}\np_val: {}'.format(t_score, p_val))

t_score: 0.35667421873586497
p_val: 0.7254826114574362


### * Paired T-test

In [33]:
# Ho: The average weight before and after the weight loss program is same. No significance difference.
# Ha: There is a significance difference in the weight before and after the weight loss program 

In [34]:
pre_weightloss = [140,120,150,125,90,100,120,150]
post_weightloss = [100,90,100,80,65,75,85,110]

t_score, p_val = stats.ttest_rel(pre_weightloss,post_weightloss)
if p_val<=0.05:
    print('We reject the null hypothesis saying that there is a significance difference in the weight before and after the weight loss program')
else:
    print('We do not reject the null hypothesis saying that there is a significance difference in the weight before and after the weight loss program')

We reject the null hypothesis saying that there is a significance difference in the weight before and after the weight loss program


### C] ANOVA (same as 2-sample but input are more than 2 so we use anova)

In [35]:
# Ho: The average marks of students from class c are more than class A and Class B.
# Ha: The average marks of students from class c do not have more than class A and Class B.

In [36]:
Class_A = (12,15,14,16,13,18,48,26,15,78)
Class_B = (15,45,89,26,31,54,12,26,32,21)
Class_C = (89,78,89,95,78,89,87,100,98,78)

t_score, p_val = stats.f_oneway(Class_A,Class_B,Class_C)
print(p_val)
if p_val<=0.05:
    print('We reject the null hypothesis saying that The average marks of students from Class_C are not more than class A and Class B.')
else:
    print('We do not reject the null hypothesis saying that The average marks of students from class c are more than class A and Class B.')

6.128027099371702e-08
We reject the null hypothesis saying that The average marks of students from Class_C are not more than class A and Class B.
